version: '2'
services:
  geoserver:
    image: dimasciput/haitidata_geoserver:clustering
    environment:
      DJANGO_URL: ${SITE_URL}:${SITE_PORT}
      SITEURL: ${SITE_URL}:${SITE_PORT}
      GEOSERVER_BASE_URL: ${SITE_URL}:${GEOSERVER_PORT}/geoserver/
    stdin_open: true
    volumes:
    - ${GEOSERVER_DATA}:/geoserver_data/data
    tty: true
    links:
    - postgres:postgres
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
  geoserver-balancer:
    image: rancher/lb-service-haproxy:v0.7.9
    ports:
    - ${GEOSERVER_PORT}:${GEOSERVER_PORT}/tcp
    expose:
    - 8080:8080/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
  django:
    image: kartoza/haitidata_django:latest
    environment:
      DATABASE_HOST: postgres
      DATABASE_NAME: gis
      DATABASE_PASSWORD: ${POSTGRES_PASS}
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      DATABASE_USERNAME: ${POSTGRES_USER}
      DJANGO_SETTINGS_MODULE: core.settings.prod_docker
      GEOSERVER_BASE_URL: ${SITE_URL}:${GEOSERVER_PORT}/geoserver/
      GEOSERVER_PUBLIC_LOCATION: ${SITE_URL}:${SITE_PORT}/api/geoserver/
      LC_ALL: en_US.UTF-8
      RABBITMQ_HOST: rabbitmq
      SITEURL: ${SITE_URL}:${SITE_PORT}
    stdin_open: true
    volumes:
    - django-static-data:/home/web/static:rw
    - django-media-data:/home/web/media:rw
    tty: true
    links:
    - postgres:postgres
    - geoserver-balancer:geoserver-balancer
    command:
    - /entry-point.sh
    labels:
      io.rancher.container.pull_image: always
  elasticsearch:
    image: elasticsearch
  nginx:
    image: dimasciput/haitidata_nginx:latest
    stdin_open: true
    volumes:
    - django-static-data:/home/web/static:ro
    - django-media-data:/home/web/media:ro
    tty: true
    links:
    - django:django
    - geoserver-balancer:geoserver
    ports:
    - ${SITE_PORT}:8080/tcp
    labels:
      io.rancher.container.pull_image: always
  rabbitmq:
    image: rabbitmq
  postgres:
    image: dimasciput/haitidata_db
    environment:
      PASS: ${POSTGRES_PASS}
      POSTGRES_PASS: ${POSTGRES_USER}
      POSTGRES_USER: ${POSTGRES_PASS}
      USERNAME: ${POSTGRES_USER}
    volumes:
    - /backups:/backups
  dbbackups:
    image: kartoza/pg-backup:9.4
    environment:
      DUMPPREFIX: HAITIDATA
      PGDATABASE: gis
      PGHOST: db
      PGPASSWORD: ${POSTGRES_USER}
      PGPORT: '5432'
      PGUSER: ${POSTGRES_PASS}
    stdin_open: true
    volumes:
    - /backups:/backups
    tty: true
    links:
    - postgres:db
    labels:
      io.rancher.container.pull_image: always
