name: GeoContext
description: A django app to retrieve context for spatial feature
version: 1
category: GIS
maintainer: Kartoza (Pty) Ltd. - Dimas Ciputra, dimas@kartoza.com
license: GPL v3
projectURL: https://github.com/kartoza/geocontext
