name: "Generic GeoNode"
description: |
    Generic GeoNode deployment - Kartoza Fork.
version: "v1"
category: "GIS"
maintainer: "Kartoza.com (forked from Geo-Solutions.it)"
license: "GPL"
projectURL: "http://geonode.org"
